# Generated by Django 5.1.3 on 2024-11-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
