# Generated by Django 5.1.3 on 2024-11-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_category_tbl_subcategory'),
        ('Guest', '0002_alter_tbl_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('shop_id', models.CharField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=50, unique=True)),
                ('shop_email', models.EmailField(max_length=254, unique=True)),
                ('shop_password', models.CharField(max_length=255)),
                ('shop_photo', models.URLField()),
                ('shop_contact', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=255)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
